name: publish

on:
  workflow_dispatch:
    push:
      branches: ['*']
      tags: ['v[0-9]+.[0-9]+.[0-9]+']
    pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Checkout
        uses: actions/checkout@v2

      - run: yarn install

      - name: Build and push Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          dockerfile: Dockerfile
          repository: shieldingtrans/relayer
          tag_with_ref: true
          tags: candidate
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
